development:
  adapter: postgresql
  host: localhost
  username: postgres
  password: gkgk
  database: swell_social_dev

test:
  adapter: postgresql
  host: localhost
  username: postgres
  password: gkgk
  database: swell_social_test
